name:        timely
version:     v0.1.0
summary:     summarise timestamped text-occurrence over a time-range.
confinement: strict
description: summarise timestamped text-occurrence over a time-range.

apps:
  timely:
    command: bin/timely

parts:
  timely:
    plugin: nodejs
    node-packages:
      - rgrannell1/timely
